//! Calibrated radial routes: piecewise-linear tables over r ∈ [0, 1].
//!
//! Row layout: `[r, p0..p7, cx, cy, cz, L, tau, omega]`.
//! The data between the markers is generated by
//! `cargo run --release --example calibrate` — do not edit it by hand.

pub const COLS: usize = 15;

// BEGIN GENERATED
pub const ANCHORS: [usize; 1] = [0];
pub const KAPPA0: f64 = 0.15;
static ROUTES: [&[[f32; COLS]]; 5] = [
    &[
        [0.0, 1.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0, 1.7, 1.5],
        [1.0, 0.12, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0, 1.7, 1.5],
    ],
    &[],
    &[],
    &[],
    &[],
];
// END GENERATED

/// One interpolated row of a route.
#[derive(Clone, Copy, Debug)]
pub struct Sample {
    pub p: [f32; 8],
    pub c: [f32; 3],
    pub l: f32,
    pub tau: f32,
    pub omega: f32,
}

/// Linear interpolation of a kind's route at radius `r` (clamped to [0, 1]).
pub fn sample(kind: usize, r: f64) -> Sample {
    let rows = ROUTES[kind];
    let r = r.clamp(0.0, 1.0) as f32;
    let hi = rows.partition_point(|row| row[0] <= r).clamp(1, rows.len() - 1);
    let (a, b) = (&rows[hi - 1], &rows[hi]);
    let t = ((r - a[0]) / (b[0] - a[0])).clamp(0.0, 1.0);
    let mut v = [0.0f32; COLS];
    for i in 0..COLS {
        v[i] = a[i] + (b[i] - a[i]) * t;
    }
    Sample {
        p: [v[1], v[2], v[3], v[4], v[5], v[6], v[7], v[8]],
        c: [v[9], v[10], v[11]],
        l: v[12],
        tau: v[13],
        omega: v[14],
    }
}
